---
title: "PokemonGo customer analytics"
author: '[Leonard Henriquez](https://github.com/leonard-henriquez/), [Adrien Lequiller](https://github.com/adrienlequiller) & [Eddy Ohayon](https://github.com/Eddoha55)'
date: "`r Sys.Date()`"
output: pdf_document
always_allow_html: yes
---

```{r message=FALSE, warning=FALSE, include=FALSE}
# Options
knitr::opts_chunk$set(cache = TRUE, warning=FALSE)

# Libraries
library(dplyr)
library(tidyr)
library(ggplot2)
```

First, let's start by reading the data
```{r}
# Import customers' data
customer        <- read.csv("input/customerdata.csv" )

# Import transactions
tx.fall         <- read.csv("input/fallfintrx.csv"   )
tx.summer       <- read.csv("input/summerfintrx.csv" )
tx.all <- tx.fall %>% union(tx.summer)

# Import sessions
sessions.fall   <- read.csv("input/fallsesstrx.csv"  )
sessions.summer <- read.csv("input/summersesstrx.csv")
sessions.all <- sessions.fall %>% union(sessions.summer)
```

```{r}
summary(customer)
```
```{r}
# Added monetary value of each transaction and converted data
tx.all <- tx.fall %>% mutate(Value = c(2.99, 4.99, 9.99, 25, 99)[ProductID], Date = as.Date(Date))

summary(tx.all)
```


```{r}
# Calculated RFM based on all transactions (summer and fall)
# for each customer (who made at least one transaction)
customer.RFM <- tx.all %>%
  inner_join(customer, by = 'CustomerID') %>%
  group_by(CustomerID) %>%
  summarise(Recency = max(Date), Frequency = n(), Monetary = sum(Value))

summary(customer.RFM)
```


```{r}
# Fetch all active customer
customerID.active <- sessions.summer %>% select(CustomerID) %>% distinct(CustomerID)

summary(customerID.active)
```

```{r}
# Calculate the RFM value for active customers
customer.active.RFM <- customerID.active %>%
  left_join(customer.RFM, by = "CustomerID") %>%
  mutate(Frequency = replace_na(Frequency, 0), Monetary = replace_na(Monetary, 0))

summary(customer.active.RFM)
```


```{r}
customer.active <- customer.active.RFM %>%
  left_join(customer, by = 'CustomerID') %>%
  select(-X)

customer.stats <- sessions.all %>%
  group_by(CustomerID) %>%
  select(-c(X, PlayID, Date)) %>%
  summarise_all(funs(sum))

customer.active <- customer.active %>%
  left_join(customer.stats, by = "CustomerID")

summary(customer.active)
```





```{r}
# Registration period
days_in_registration_period <- as.numeric(as.Date(max(sessions.all$Date)) - as.Date(min(as.Date(customer$Registrationdate))))

# Period of time of transactions
days_in_period <- as.numeric(as.Date(max(sessions.all$Date)) - as.Date(min(sessions.all$Date)))

total_daily_revenues <- sum(tx.all$Value) / days_in_period
total_daily_marketing_cost <- 0.15 * total_daily_revenues
total_marketing_cost_in_registration_period <- total_daily_marketing_cost * days_in_registration_period
AC = total_marketing_cost_in_registration_period / count(customer)
AC
```


```{r}
CLV <- function (r) {
  # Period of time to convert revenue to (annual) recurring revenue
  days_in_period <- as.numeric(as.Date(max(sessions.all$Date)) - as.Date(min(sessions.all$Date)))
  rr <- r * 365 / days_in_period

  # Customer value
  AC <- 0       # Customer acquisition costs
  rc <- 0       # Recurring cost
  m  <- rr - rc # Customer recurring contribution margin
  r  <- 0.5     # Retention probability for the customer
  t  <- 5       # Number of years 'out' to estimate
  d  <- 0.1     # Discount rate (Cost of Capital)

  clv <- AC
  for(i in 0:t) {
    clv <- clv+((r^i)*m/(1+d)^i)
  }
  return(clv)
}
```


```{r}
clv <- customer.active %>% mutate(CLV = CLV(Monetary))
summary(clv)
```

```{r}
ggplot(customer.active)+aes(x=CustomerType,fill=as.factor(Sex))+geom_bar()
ggplot(customer.active)+aes(x=Sex,fill=as.factor(CustomerType))+geom_bar()
```
